version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - MavenRepo:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: GhostDB
    volumes:
      - DB:/var/lib/mysql

    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "user", "--password=password"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  MavenRepo:
  DB:

